language: go

go:
  - tip
  - 1.8

install:
  - go get -t ./...
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/client9/misspell/cmd/misspell
  - go get github.com/golang/lint/golint

script:
  - diff <(echo -n) <(gofmt -s -d .)
  - ineffassign .
  - misspell -error .
  - go vet ./...
  - go test -race ./...

after_script:
  - golint ./...